### ISSUE TITLE
Two questions:TypeError: forward() missing 1 required positional argument: 'batch_dict' and failed to parse onnx model file, please check the onnx version and trt support op!

### ISSUE THREAD

**Issue by JonathanFK981** [NVIDIA-AI-IOT/CUDA-PointPillars#97]
Environment:
```txt
Ubuntu 22.04 x86_64
CUDA 11.6
TensorRT 8.6.1.6
cumm-cu116=0.4.11
spconv-cu116=2.3.6
python=3.8.17
torch=1.13.1+cu116
torch2trt=0.4.0
torchaudio=0.13.1+cu116
torchvision=0.14.1+cu116
onnx=1.13.1
onnx-graphsurgeon=0.3.27
onnx-simplifier=0.4.33
onnxconverter-common=1.13.0
onnxruntime =1.13.1
onnxsim=0.4.33
pcdet=0.6.0+bce886d
SharedArray=3.2.3
```
Q1:When I run `python /home/CUDA-PointPillars/tool/exporter.py --ckpt /home/CUDA-PointPillars/tool/pointpillar_7728.pth`,the error is 
```txt
Traceback (most recent call last):
  File "/home/CUDA-PointPillars/tool/exporter.py", line 175, in <module>
    main()
  File "/home/CUDA-PointPillars/tool/exporter.py", line 151, in main
    torch.onnx.export(model,       # model being run
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/software/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'batch_dict'
```
Q2:When I run 'mkdir build && cd build && cmake .. && make' and run `demo`,the error is 
```txt
GPU has cuda devices: 1
----device id: 0 info----
  GPU : NVIDIA GeForce GTX 1660 SUPER 
  Capbility: 7.5
  Global memory: 5933MB
  Const memory: 64KB
  SM in a block: 48KB
  warp size: 32
  threads in a block: 1024
  block dim: (1024,1024,64)
  grid dim: (2147483647,65535,65535)

Building TRT engine.
[libprotobuf ERROR /home/TensorRT/build/third_party.protobuf/src/third_party.protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format onnx2trt_onnx.ModelProto: 1:9: Message type "onnx2trt_onnx.ModelProto" has no field named "version".
trt_infer: parsers/onnx/ModelImporter.cpp:733: Failed to parse ONNX model from file: ../model/pointpillar.onnx
: failed to parse onnx model file, please check the onnx version and trt support op!

```

**Comment by Dreamdreams8** [comment]
换到pcdetv0.5.0可以解决。

**Comment by JonathanFK981** [comment]
> 换到pcdetv0.5.0可以解决。

好的谢谢，已经解决了

**Comment by liveforday** [comment]
@JonathanFK981  I  have  a problem `error: THC/THC.h no such a file ` when I use pytorch==1.13.1  How to slove it?
